"""Public API for Aeloon's pure-Python agent harness."""

from aeloon_core.harness.compaction import (
    CompactionResult,
    CompactionSettings,
    estimate_context_tokens,
)
from aeloon_core.harness.core import AgentHarness, AgentHarnessPhase
from aeloon_core.harness.prompt import build_system_prompt, format_skills_for_system_prompt
from aeloon_core.harness.providers import (
    DEEPSEEK_MODELS,
    DEEPSEEK_V4_FLASH,
    DEEPSEEK_V4_PRO,
    DeepSeekProvider,
    ScriptedProvider,
    get_deepseek_model,
)
from aeloon_core.harness.resources import ResourceLoader
from aeloon_core.harness.session import (
    JsonlSessionRepository,
    Session,
    SessionContext,
    SessionMetadata,
)
from aeloon_core.harness.tools import (
    ALL_TOOL_NAMES,
    DEFAULT_ACTIVE_TOOLS,
    create_all_tools,
)
from aeloon_core.harness.types import (
    AgentMessage,
    AgentTool,
    AssistantMessage,
    AssistantStreamEvent,
    HarnessError,
    HarnessEvent,
    HarnessEventType,
    ImageContent,
    Model,
    PromptTemplate,
    Provider,
    ProviderContext,
    ProviderError,
    Resources,
    SessionError,
    Skill,
    StreamOptions,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolResult,
    ToolResultMessage,
    Usage,
    UserMessage,
    content_from_dict,
    message_from_dict,
    message_to_dict,
)

__all__ = [
    "ALL_TOOL_NAMES",
    "DEFAULT_ACTIVE_TOOLS",
    "DEEPSEEK_MODELS",
    "DEEPSEEK_V4_FLASH",
    "DEEPSEEK_V4_PRO",
    "AgentHarness",
    "AgentHarnessPhase",
    "AgentMessage",
    "AgentTool",
    "AssistantMessage",
    "AssistantStreamEvent",
    "CompactionResult",
    "CompactionSettings",
    "DeepSeekProvider",
    "HarnessError",
    "HarnessEvent",
    "HarnessEventType",
    "ImageContent",
    "JsonlSessionRepository",
    "Model",
    "PromptTemplate",
    "Provider",
    "ProviderContext",
    "ProviderError",
    "ResourceLoader",
    "Resources",
    "ScriptedProvider",
    "Session",
    "SessionContext",
    "SessionError",
    "SessionMetadata",
    "Skill",
    "StreamOptions",
    "TextContent",
    "ThinkingContent",
    "ToolCall",
    "ToolResult",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "build_system_prompt",
    "content_from_dict",
    "create_all_tools",
    "estimate_context_tokens",
    "format_skills_for_system_prompt",
    "get_deepseek_model",
    "message_from_dict",
    "message_to_dict",
]
