"""Public contracts for one stateless, vendor-neutral agent run."""

from aeloon_runtime.core.compaction import (
    CompactionReason,
    ContextCompactor,
    ContextPolicy,
    ContextUpdate,
    is_context_overflow,
    should_compact,
)
from aeloon_runtime.core.context_stats import (
    cache_statistics,
    context_statistics,
    estimate_context_tokens,
    estimate_tokens,
)
from aeloon_runtime.core.control import RunController
from aeloon_runtime.core.inference_runtime import (
    InferenceRuntime,
    collect_assistant,
    model_to_dict,
)
from aeloon_runtime.core.runner import RunHooks, RunRequest, RunResult, run_agent
from aeloon_runtime.core.types import (
    AgentMessage,
    AssistantContent,
    AssistantMessage,
    AssistantStreamEvent,
    ImageContent,
    InferenceContext,
    InferenceError,
    InferencePort,
    Model,
    QueueMode,
    RunError,
    RunEvent,
    RunEventSink,
    RunEventType,
    RunHook,
    StopReason,
    StreamOptions,
    TextContent,
    ThinkingContent,
    ThinkingLevel,
    Tool,
    ToolCall,
    ToolResult,
    ToolResultMessage,
    Usage,
    UserMessage,
    content_from_dict,
    content_to_dict,
    message_from_dict,
    message_to_dict,
    now_ms,
)

__all__ = [
    "AgentMessage",
    "AssistantContent",
    "AssistantMessage",
    "AssistantStreamEvent",
    "CompactionReason",
    "ContextCompactor",
    "ContextPolicy",
    "ContextUpdate",
    "ImageContent",
    "InferenceContext",
    "InferenceError",
    "InferencePort",
    "InferenceRuntime",
    "Model",
    "QueueMode",
    "RunController",
    "RunError",
    "RunEvent",
    "RunEventSink",
    "RunEventType",
    "RunHook",
    "RunHooks",
    "RunRequest",
    "RunResult",
    "StopReason",
    "StreamOptions",
    "TextContent",
    "ThinkingContent",
    "ThinkingLevel",
    "Tool",
    "ToolCall",
    "ToolResult",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "cache_statistics",
    "collect_assistant",
    "content_from_dict",
    "content_to_dict",
    "context_statistics",
    "estimate_context_tokens",
    "estimate_tokens",
    "is_context_overflow",
    "message_from_dict",
    "message_to_dict",
    "model_to_dict",
    "now_ms",
    "run_agent",
    "should_compact",
]
